kantv-ai/kantv

.gitignore
README.md
VERSION.txt
build/envsetup.sh
cdeosplayer/cdeosplayer-lib/src/main/java/cdeos/media/player/CDEUtils.java
cdeosplayer/cdeosplayer-lib/src/main/java/cdeos/media/player/KANTVVersion.java
cdeosplayer/constants.gradle
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/player/ffplayer/FFPlayerView.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/activities/MainActivity.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/ASRResearchFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/settings/DownloadModel.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/settings/PlaySettingFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/settings/SystemSettingFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/settings/VoiceSettingFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/utils/Settings.java
cdeosplayer/kantv/src/main/res/layout/fragment_personal.xml
cdeosplayer/kantv/src/main/res/values-en/strings.xml
cdeosplayer/kantv/src/main/res/values-en/strings_pref.xml
cdeosplayer/kantv/src/main/res/values-zh/strings.xml
cdeosplayer/kantv/src/main/res/values-zh/strings_pref.xml
cdeosplayer/kantv/src/main/res/values/strings.xml
cdeosplayer/kantv/src/main/res/values/strings_pref.xml
cdeosplayer/kantv/src/main/res/xml/settings_play.xml
cdeosplayer/kantv/src/main/res/xml/settings_voice.xml
external/whispercpp/CMakeLists.txt
external/whispercpp/how-to-use-main.sh
external/whispercpp/jni/whispercpp-jni-impl.cpp
external/whispercpp/jni/whispercpp-jni.h
external/whispercpp/whisper.cpp
release/README.md

UI:enable APK user download user-specified GGML model file and use user-specified model file to do online-TV transcription

---

cdeosplayer/kantv/src/main/java/com/cdeos/kantv/app/IApplication.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/player/ffplayer/FFPlayerView.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/settings/ASRSettingFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/utils/Settings.java
external/.gitignore
external/whispercpp/jni/whispercpp-jni-impl.cpp

sometimes whispercpp would produce sketchy/incorrect/repeat tokens or app would crash suddenly

real real-time transcription(real-time subtitle) with English online-TV for the first time on Xiaomi14 but buf-fix is still required

---

.gitignore
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/LLMResearchFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/settings/DownloadModel.java
docs/FAQ.md
external/whispercpp/CMakeLists.txt
external/whispercpp/build-android-jni-lib.sh
external/whispercpp/diff-with-upstream-whispercpp.sh
external/whispercpp/sync-with-upstream-whispercpp.sh

release: official release v1.3.5 after fix some minor issues

release: official release v1.3.5 after fix some minor issues

---

README.md
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/ASRResearchFragment.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/LLMResearchFragment.java
cdeosplayer/kantv/src/main/res/layout/fragment_asr.xml
cdeosplayer/kantv/src/main/res/layout/fragment_llm.xml
cdeosplayer/kantv/src/main/res/values/arrays.xml
external/ggml/jni/ggml-jni-impl.cpp
external/ggml/llamacpp/Makefile
external/ggml/llamacpp/diff-with-upstream-llamacpp.sh
external/ggml/llamacpp/ggml-common.h
external/ggml/llamacpp/llama.cpp
external/ggml/llamacpp/sync-with-upstream-llamacpp.sh

upstream llama.cpp changed so quickly. should keep a stable branch here to avoid something issue.

sanity-check:fix issues caused by sync with upstream llama.cpp

---

README.md

doc:update toplevel README.md to comply compliance policy in llama.cpp

doc:update toplevel README.md to comply compliance policy in llama.cpp

---

README.md

doc: update toplevel README.md to comply compliance policy in llama.cpp

doc: update toplevel README.md to comply compliance policy in llama.cpp

---

README.md
cdeosplayer/gradle.properties
cdeosplayer/gradle/wrapper/gradle-wrapper.properties
prebuilts/.gitignore

Update gradle wrapper to 7.3 and JDK-17.
Fix ButterKnife compatibility issue with a workaround.

Update JDK to 17

---

README.md
build/Dockerfile

Add Dockerfile and update build instructions.

Add docker build environment.

---

cdeosplayer/cdeosplayer-lib/src/main/java/org/ggml/ggmljava.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/AIResearchFragment.java
core/ggml/jni/ggml-jni-impl.cpp
core/ggml/jni/ggml-jni.c
core/ggml/jni/ggml-jni.h
core/ggml/jni/llm-inference.cpp
core/ggml/jni/minicpmv-cli.cpp

ggml-jni: fix ui issue when user cancel time-consuming LLM bench task in ui layer

---

cdeosplayer/cdeosplayer-lib/src/main/java/cdeos/media/player/CDEUtils.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/app/IApplication.java
cdeosplayer/kantv/src/main/java/com/cdeos/kantv/ui/fragment/AIResearchFragment.java
core/ggml/CMakeLists.txt
core/ggml/jni/ggml-jni-impl-external.cpp
core/ggml/jni/ggml-jni-impl.cpp
core/ggml/jni/ggml-jni.c
core/ggml/jni/ggml-jni.h
core/ggml/jni/llm-inference.cpp
core/ggml/jni/minicpmv-cli.cpp
core/ggml/llamacpp/ggml-qnn.cpp
core/ggml/llamacpp/ggml-qnn.h
core/ggml/whispercpp/whisper.cpp

validated on Xiaomi 14 with following case:
mulmat with QNN CPU/GPU/NPU backend
qnn-auto-ut(add, mulmat) with QNN CPU/GPU/NPU backend
whispercpp inference with QNN CPU/GPU/NPU backend
llamacpp inference with QNN CPU/GPU/NPU backend
all above testcases works fine as expected

ggml-qnn: refine code and keep sync ggml-qnn.cpp&ggml-qnn.h between local and PR in upstream

---

core/ggml/jni/ggml-jni-impl-external.cpp
core/ggml/llamacpp/ggml-qnn.cpp
core/ggml/llamacpp/ggml-qnn.h
core/ggml/llamacpp/tests/ggml-qnn-ut-in-kantv/.gitignore
core/ggml/llamacpp/tests/ggml-qnn-ut-in-kantv/CMakeLists.txt
core/ggml/llamacpp/tests/ggml-qnn-ut-in-kantv/README.md
core/ggml/llamacpp/tests/ggml-qnn-ut-in-kantv/build-ggml-qnn.sh
core/ggml/llamacpp/tests/ggml-qnn-ut-in-kantv/run-ggml-qnn.sh
core/ggml/llamacpp/tests/ggml-qnn-ut-in-kantv/test-qnn-ops.cpp
core/ggml/llamacpp/tests/ggml-qnn/README.md
core/ggml/llamacpp/tests/ggml-qnn/test-qnn-ops.cpp
core/ggml/whispercpp/whisper.cpp
tools/run_ndkstack.sh

1. ggml-qnn.cpp should/might be bug-free now(fix a stupid bug --- which could case crash or memory leak (comment a special LoC as a workaround to fix crash) --- in ggml-qnn.cpp)
2. refine the codes for purpose of follow the coding style in upstream more strictly
3. add a more complicated/proven Android command line UT(whisper.cpp using QNN backend in Android command line mode --- without third-party Termux) and it also passed on Xiaomi14(Qualcomm SM8650-AB Snapdragon 8 Gen 3) which similar to UT in Android APK on 04/22/2024.
```
[ggml_qnn_can_handle_op, 2084]: GGML_OP_MUL_MAT
[ggml_qnn_can_handle_op, 2089]: src0      tensor_737: type = 8 ( q8_0) ne =   384 x  1536 x     1, nb = (   34,   408, 626688)
[ggml_qnn_can_handle_op, 2094]: src1     tensor_7718: type = 0 (  f32) ne =   384 x     1 …
```

ggml-qnn: refine Android command line UT program

---

android/constants.gradle
android/kantvplayer/src/main/assets/config.json
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/player/ffplayer/FFPlayerView.java
release/README.md
release/VERSION.txt

test model is **[qwen2.5-3b-instruct-q4_0.gguf](https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/tree/main)**. 
validate following features on Android phone equipped with Snapdragon 8Gen3 and Snapdragon 8Elite:
- TV playback
- TV playback + TV recording
- local playback with recorded video file
- TV playback +  AI-subtitle
- TV playback + TV recording + AI-subtitle
- ASR inference(through whisper.cpp) benchmark with ggml backend & cDSP backend
- LLM inference(through llama.cpp) benchmark with ggml  backend & cDSP backend
- 2D graphic benchmark
- video encode benchmark
- video encode benchmark and create code-generated video file
- local playback with code-generated video file
dev envs:
QNN SDK is v2.33.0.**250327**,Hexagon SDK is v6.2.0.1, Android NDK is android-ndk-r28. 
QNN SDK and …

project: release v1.6.6

---

android/kantvplayer-lib/src/main/java/kantvai/media/player/KANTVLLMModel.java
android/kantvplayer-lib/src/main/java/kantvai/media/player/KANTVUtils.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/AIResearchFragment.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/LLMResearchFragment.java
android/kantvplayer/src/main/res/values/arrays.xml

- refine UI and make UI code more clear
- make UI code more easily customized for new LLM model(add and verify new LLM model on Android phone more easier from now on)

ui: refine UI

---

README.md
android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIModel.java
android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIModelMgr.java
android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIUtils.java
android/kantvplayer-lib/src/main/java/kantvai/media/player/KANTVMediaGridAdapter.java
android/kantvplayer-lib/src/main/java/kantvai/media/player/KANTVUtils.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/AIResearchFragment.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/TVGridFragment.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/settings/DownloadModel.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/settings/LLMSettingFragment.java
android/kantvplayer/src/main/res/values-en/strings_pref.xml
android/kantvplayer/src/main/res/values-zh/strings_pref.xml
android/kantvplayer/src/main/res/values/strings_pref.xml

- bugfix in native(rendering multi-line string)
- refine logic of download LLM in APK
- support download Gemma3-12B, Qwen1.5-1.8B, Qwen2.5-3B, Qwen2.5-VL-3B,  Qwen3-4B, Qwen3-8B in APK

java: refine LLM download

---

android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIModelMgr.java
core/ggml/CMakeLists.txt
core/ggml/jni/realtime-video-recognition.cpp

- better understanding with implementation of ngxson's MTMD in llama.cpp(his API is clear and easy to use after understanding some tech details in his implementation of MTMD)
- refine the implementation of "realtime" video recognition on Android phone: using ngxson's MTMD API directly and avoid write image data to storage.
https://github.com/ngxson/smolvlm-realtime-webcam
https://github.com/kantv-ai/kantv/pull/327
https://github.com/kantv-ai/kantv/pull/329
- stability issue between UI layer and native layer: APP would crash when toggle back and forth frequently between different UI and corner case.
- non-block MTMD inference

feature: realtime video recognition on Android phone via MTMD in llama.cpp --- step3

---

.github/workflows/build.yml
android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIModelMgr.java
android/kantvplayer/src/main/assets/tv.xml
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/AIResearchFragment.java
build/build-all.sh
build/prebuild.sh
core/build-android-jni-lib.sh
core/ggml/CMakeLists.txt
core/ggml/jni/ggml-jni.c
core/ggml/jni/ndkcamera.cpp
core/ggml/whispercpp/whisper.cpp
docs/how-to-build.md

- refine build scripts, add prebuilt-apk for Android phone equipped without Qualcomm mobile SoC in Github-CI
- fix a minor issue in UI
- remove CGTN in tv.xml because it's prohibited to access.

ci: add prebuilt-apk for Android phone equipped without Qualcomm mobile SoC

---

android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIUtils.java
android/kantvplayer-lib/src/main/java/kantvai/ai/ggmljava.java
android/kantvplayer-lib/src/main/java/kantvai/media/player/KANTVDRM.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/settings/LLMSettingFragment.java
android/kantvplayer/src/main/res/xml/settings_llm.xml
core/ggml/jni/ggml-jni-impl-external.cpp
core/ggml/jni/ggml-jni.c
core/ggml/jni/ggml-jni.h
core/ggml/jni/llm-inference.cpp

- adjust temperature and top-p in LLM Setting

java: adjust temperature and top-p in LLM Setting

---

android/kantvplayer-lib/src/main/java/kantvai/ai/ggmljava.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/activities/MainActivity.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/LLMResearchFragment.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/settings/LLMSettingFragment.java
core/ggml/jni/ggml-jni.c
core/ggml/jni/ndkcamera.cpp
core/ggml/jni/realtime-video-recognition.cpp

- fix stability bug in realtime multimodal inference
there is a potential deadlock when toggle back and forth frequently between UI-with-realtime-multimodal-inference and other UI

stability: fix stability bug in realtime multimodal inference

---

android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIUtils.java
android/kantvplayer-lib/src/main/java/kantvai/ai/ggmljava.java
android/kantvplayer-lib/src/main/java/kantvai/media/player/KANTVUtils.java
core/ggml/CMakeLists.txt
core/ggml/jni/ggml-jni.c
core/ggml/jni/ggml-jni.h
core/ggml/jni/myndkcamera.cpp
core/ggml/jni/myndkcamera.h
core/ggml/jni/realtime-video-recognition.cpp

- pre-cache multimodal model in realtime MTMD inference to improve performance of MTMD inference
- make implementation of realtime MTMD inference more clear

jni: pre-cache multimodal model in realtime MTMD inference

---

android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIModelMgr.java
android/kantvplayer-lib/src/main/java/kantvai/ai/KANTVAIUtils.java
android/kantvplayer/build.gradle
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/app/IApplication.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/ui/fragment/settings/LLMSettingFragment.java
android/kantvplayer/src/main/java/com/kantvai/kantvplayer/utils/Settings.java
android/kantvplayer/src/main/res/values-en/strings_pref.xml
android/kantvplayer/src/main/res/values-zh/strings_pref.xml
android/kantvplayer/src/main/res/values/strings_pref.xml
android/kantvplayer/src/main/res/xml/settings_llm.xml
core/ggml/jni/ggml-jni-impl-external.cpp

refine hf_endpoint in UI for users/developers/AI experts from China: download AI models in the APK directly.

UI: refine hf_endpoint for users/developers/AI experts from China
